export const types = Object.freeze({
    PERSON_START_FETCH:'PERSON_START_FETCH',
    PERSON_STOP_FETCH:'PERSON_STOP_FETCH',
    PERSON_FILL:'PERSON_FILL',
    PERSON_ERROR_FETCH:'PERSON_ERROR_FETCH',
    PERSON_FETCH_ASYNC:'PERSON_FETCH_ASYNC',
})