export const types = Object.freeze({
    //Sync
    PLANETS_START_FETCH: 'PLANETS_START_FETCH',
    PLANETS_FILL:'PLANETS_FILL',
    PLANETS_STOP_FETCH: 'PLANETS_STOP_FETCH',
    PLANETS_ERROR_FETCH: 'PLANETS_ERROR_FETCH',

    //Async
    PLANETS_FETCH_ASYNC: 'PLANETS_FETCH_ASYNC'
})