export const types = Object.freeze({
    //Sync
    STARSHIP_START_FETCH: 'STARSHIP_START_FETCH',
    STARSHIP_FILL:'STARSHIP_FILL',
    STARSHIP_STOP_FETCH: 'STARSHIP_STOP_FETCH',
    STARSHIP_ERROR_FETCH: 'STARSHIP_ERROR_FETCH',

    //Async
    STARSHIP_FETCH_ASYNC: 'STARSHIP_FETCH_ASYNC'
})