export const types = Object.freeze({
    FILMS_START_FETCH: 'FILMS_START_FETCH',
    FILMS_STOP_FETCH: 'FILMS_STOP_FETCH',
    FILMS_FILL: 'FILMS_FILL',
    FILMS_ERROR: 'FILMS_ERROR',
    FILMS_ASYNC_FETCH: 'FILMS_ASYNC_FETCH'
})