export const types = Object.freeze({
    PEOPLE_START_FETCH:'PEOPLE_START_FETCH',
    PEOPLE_STOP_FETCH:'PEOPLE_STOP_FETCH',
    PEOPLE_FILL:'PEOPLE_FILL',
    PEOPLE_ERROR_FETCH:'PEOPLE_ERROR_FETCH',
    PEOPLE_FETCH_ASYNC:'PEOPLE_FETCH_ASYNC',
})